export ELASTIC_USERNAME=elastic
export ELASTIC_PASSWORD=xxxxxxxxxx
export ELASTIC_CLOUD_ID=xxxxxxxxxxx
export RRF_URL=xxxxxxxxx
export RRF_USERNAME=admin
export RRF_PASSWORD=xxxxxxxxxx
export OPENAI_API_KEY=xxxxxxxxxxxxxx
